{% set python_min = "3.10" %}
{% set name = "mdtop" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SimonBoothroyd/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 114bb6e9305c3dee0e62a8bfda82bcab76e2bdbf8331eb12b95c97f11dda92a1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation 
  number: 0

requirements:
  build:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm >=8
  run:
    - python >={{ python_min }}
    - numpy
    - pandas
    - pyparsing
    - rdkit
    - scipy
    - openmm >=8.0.0

test:
  imports:
    - mdtop
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://github.com/SimonBoothroyd/mdtop
  summary: 'Store topological information about a system to simulate.'
  description: |
    A framework aims to provide a simple, modern, and flexible way to store
    topological information about a system to simulate.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://simonboothroyd.github.io/mdtop/latest/
  dev_url: https://github.com/SimonBoothroyd/mdtop

extra:
  recipe-maintainers:
    - SimonBoothroyd
